name: airbnb-project
channels:
  - conda-forge
dependencies:
  - python=3.12

  # Core data tools
  - pandas
  - pyarrow
  - pyspark
  - duckdb

  # Visualization
  - matplotlib
  - seaborn
  - plotly

  # Jupyter
  - jupyterlab
  - ipykernel

  # AWS and SQL utilities
  - boto3
  - sqlalchemy

  # Optional: for profiling
  - ydata-profiling